add ubuntu 20.04, centos8 ci axes
rapidsai/gpuci-build-environment pull request #146
Opened 2020-11-24 15:34 UTC by jolorunyomi

# Summary
This PR adds support for Ubuntu 20.04 and Centos 8 to our gpuci build environment.

2020-12-02 16:45 UTC, ajschmidt8 commented
Based on Mike's comments from Slack, we should only build `centos8` and `ubuntu20.04` images for CUDA 11 and up. So you'll need to add the exclusions below to `ci/axis/rapidsai.yml` to get CI to pass here.

```yaml
  - LINUX_VER: centos8
    CUDA_VER: 10.2
  - LINUX_VER: centos8
    CUDA_VER: 10.1
  - LINUX_VER: ubuntu20.04
    CUDA_VER: 10.2
  - LINUX_VER: ubuntu20.04
    CUDA_VER: 10.1
```

2020-12-04 21:43 UTC, mike-wendt commented
rerun tests

2020-12-04 21:44 UTC, mike-wendt requested changes
@jolorunyomi I don't see any changes to the dockerfiles to ensure we have gcc 7.5 on both Ubuntu 20.04 and CentOS 8

we need to override the default gcc to match the other images with 7.5

2020-12-08 17:28 UTC, mike-wendt commented
@jolorunyomi can you merge master into this branch? this way you'll get the config for `miniforge-cuda` so tests can pass and we can check that the `rapidsai` images here build successfully?

2020-12-08 17:30 UTC, mike-wendt commented
For me the TODOs are:

- revert the changes in https://github.com/rapidsai/gpuci-build-environment/pull/146/commits/2e3ddcda0b6a766cdfcb7d3d82217c3298ea2869
  - we need to use the compiled version we build from s3
- verify that ubuntu 20.04 has gcc 7.5 by default; ensuring that the ppa install process works on 20.04 as well
  - if not we need to update 20.04 to 7.5

2020-12-08 20:19 UTC, ajschmidt8 commented
gcc/g++ 7.5 confirmed on ubuntu20.04 ([jenkins job](https://gpuci.gpuopenanalytics.com/job/gpuci/job/gpuci-build-environment/job/rapidsai-test-build/72/BUILD_IMAGE=gpuci%2Frapidsai,CUDA_VER=11.0,DOCKER_FILE=devel.Dockerfile,FROM_IMAGE=gpuci%2Fminiconda-cuda,IMAGE_NAME=rapidsai,IMAGE_TYPE=devel,LINUX_VER=ubuntu20.04,PYTHON_VER=3.7,RAPIDS_CHANNEL=rapidsai-nightly,RAPIDS_VER=0.17/console), output is from [these lines](https://github.com/rapidsai/gpuci-build-environment/blob/branch-0.17/rapidsai/devel.Dockerfile#L65-L66)):

![image](https://user-images.githubusercontent.com/7400326/101536861-94288e80-3968-11eb-96a4-0d66036129a4.png)

2020-12-09 22:29 UTC, mike-wendt approved these changes

2020-12-09 22:29 UTC, mike-wendt commented
verify centos8 gcc 7.5 works

2020-12-09 22:30 UTC, merged