Add CUDA 11.1 & 11.3 gpuci/rapidsai images
rapidsai/gpuci-build-environment pull request #229
Opened 2022-01-11 20:07 UTC by AyodeAwe

This PR adds CUDA `11.1` & `11.3` `gpuci/rapidsai` images, enabling us to test previously unsupported versions of CUDA: `11.1` & `11.3` for CUDA-enhanced compatibility.

2022-01-11 20:13 UTC, ajschmidt8 reviewed
The `ci/axis/rapidsai-driver.yml` and `ci/axis/rapidsai-driver-arm64.yml` files have `DRIVER_VER` and `exclude` values that will also need to be updated.

2022-01-12 19:28 UTC, ajschmidt8 approved these changes
LGTM. Nice work. Should be all set to merge once CI passes :+1:

2022-01-13 20:40 UTC, AyodeAwe commented
rerun tests

2022-01-18 19:19 UTC, ajschmidt8 approved these changes

2022-04-20 20:14 UTC, ajschmidt8 approved these changes

2022-04-21 14:49 UTC, ajschmidt8 requested changes

2022-04-21 14:49 UTC, ajschmidt8 commented on ci/axis/rapidsai-driver-arm64.yml
> +  - 11.1
If we're not publishing `11.1` and `11.0` for ARM, then all the `11.1` and `11.0` references in this file (and other ARM files) should be removed.

2022-04-21 17:37 UTC, ajschmidt8 requested changes

2022-04-21 17:37 UTC, ajschmidt8 commented on ci/axis/miniforge-cuda-driver-arm64.yml
>      DRIVER_VER: 450
As mentioned on [this page](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html), driver versions `450` and `455` correspond to CUDA versions `11.0` and `11.1` respectively. Therefore, if we're not building `11.0` and `11.1` images for ARM, the respective driver versions should be removed throughout the ARM files as well.

2022-04-25 15:28 UTC, ajschmidt8 approved these changes

2022-04-25 17:03 UTC, merged